insert into circuito (circuitname, countryname) values ('Coffee','a');
insert into circuito (circuitname, countryname) values ('Coffee','a');
insert into circuito (circuitname, countryname) values ('Coffee','a');
insert into circuito (circuitname, countryname) values ('Coffee','a');
insert into circuito (circuitname, countryname) values ('Salmon','a');
insert into circuito (circuitname, countryname) values ('Yogurt','a');
insert into circuito (circuitname, countryname) values ('Bar En','a');
insert into circuito (circuitname, countryname) values ('Milk -','a');
insert into circuito (circuitname, countryname) values ('Ice Cr','a');
insert into circuito (circuitname, countryname) values ('Pork -','a');
insert into circuito (circuitname, countryname) values ('Soup -','a');
insert into circuito (circuitname, countryname) values ('Wine -','a');
insert into circuito (circuitname, countryname) values ('Chip -','a');
insert into circuito (circuitname, countryname) values ('Energy','a');
insert into circuito (circuitname, countryname) values ('Creme ','a');
insert into circuito (circuitname, countryname) values ('Wine -','a');
insert into circuito (circuitname, countryname) values ('Rice -','a');
insert into circuito (circuitname, countryname) values ('Ezy Ch','a');
insert into circuito (circuitname, countryname) values ('Sauce ','a');
insert into circuito (circuitname, countryname) values ('Glass ','a');
insert into circuito (circuitname, countryname) values ('Steamp','a');
insert into circuito (circuitname, countryname) values ('Napkin','a');
insert into circuito (circuitname, countryname) values ('Cilant','a');
insert into circuito (circuitname, countryname) values ('Juice ','a');
insert into circuito (circuitname, countryname) values ('Sole -','a');
insert into circuito (circuitname, countryname) values ('Bread ','a');
insert into circuito (circuitname, countryname) values ('Potato','a');
insert into circuito (circuitname, countryname) values ('Wine -','a');
insert into circuito (circuitname, countryname) values ('Apple ','a');
insert into circuito (circuitname, countryname) values ('Dc - F','a');
insert into circuito (circuitname, countryname) values ('Chocol','a');
insert into circuito (circuitname, countryname) values ('Wine -','a');
insert into circuito (circuitname, countryname) values ('Carbon','a');
